---
title: "01 - Parameter estimating by optimization"
output: 
  html_notebook:
    toc: true
    toc_float: false
    toc_depth: 4
    code_folding: hide
---

```{python setup}
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# Set default Seaborn style
sns.set()

light = pd.read_csv("/home/cla/Documentos/Vitor/DataCamp/Data-Scientist-with-Python/Datasets/speed-of-light.csv")
michelson_speed_of_light = np.array(light['velocity of light in air (km/s)'])

election = pd.read_csv("/home/cla/Documentos/Vitor/DataCamp/Data-Scientist-with-Python/Datasets/2008_election_results_swing.csv")
election['total'] = election.total_votes/900

female_literacy_fertility = pd.read_csv("/home/cla/Documentos/Vitor/DataCamp/Data-Scientist-with-Python/Datasets/female_literacy_fertility.csv")

female_literacy_fertility = female_literacy_fertility[(female_literacy_fertility['fertility'] > 1000)]
illiteracy = 100 - np.array(female_literacy_fertility['female literacy'])
fertility = np.array(female_literacy_fertility['fertility'])/1000

election['total'] = election.total_votes/900

anscombe = pd.read_csv("/home/cla/Documentos/Vitor/DataCamp/Data-Scientist-with-Python/Datasets/anscombe.csv")

def ecdf(data):
  """Compute ECDF for a one-dimensional array of measurements."""
  # Number of data points: n
  n = len(data)
  # x-data for the ECDF: x
  x = np.sort(data)
  # y-data for the ECDF: y
  y = np.arange(1, n + 1) / n
  return x, y

nohitter_times = np.array([ 843, 1613, 1101,  215,  684,  814,  278,  324,  161,  219,  545,
        715,  966,  624,   29,  450,  107,   20,   91, 1325,  124, 1468,
        104, 1309,  429,   62, 1878, 1104,  123,  251,   93,  188,  983,
        166,   96,  702,   23,  524,   26,  299,   59,   39,   12,    2,
        308, 1114,  813,  887,  645, 2088,   42, 2090,   11,  886, 1665,
       1084, 2900, 2432,  750, 4021, 1070, 1765, 1322,   26,  548, 1525,
         77, 2181, 2752,  127, 2147,  211,   41, 1575,  151,  479,  697,
        557, 2267,  542,  392,   73,  603,  233,  255,  528,  397, 1529,
       1023, 1194,  462,  583,   37,  943,  996,  480, 1497,  717,  224,
        219, 1531,  498,   44,  288,  267,  600,   52,  269, 1086,  386,
        176, 2199,  216,   54,  675, 1243,  463,  650,  171,  327,  110,
        774,  509,    8,  197,  136,   12, 1124,   64,  380,  811,  232,
        192,  731,  715,  226,  605,  539, 1491,  323,  240,  179,  702,
        156,   82, 1397,  354,  778,  603, 1001,  385,  986,  203,  149,
        576,  445,  180, 1403,  252,  675, 1351, 2983, 1568,   45,  899,
       3260, 1025,   31,  100, 2055, 4043,   79,  238, 3931, 2351,  595,
        110,  215,    0,  563,  206,  660,  242,  577,  179,  157,  192,
        192, 1848,  792, 1693,   55,  388,  225, 1134, 1172, 1555,   31,
       1582, 1044,  378, 1687, 2915,  280,  765, 2819,  511, 1521,  745,
       2491,  580, 2072, 6450,  578,  745, 1075, 1103, 1549, 1520,  138,
       1202,  296,  277,  351,  391,  950,  459,   62, 1056, 1128,  139,
        420,   87,   71,  814,  603, 1349,  162, 1027,  783,  326,  101,
        876,  381,  905,  156,  419,  239,  119,  129,  467])
```

## **Optimal parameters**

**1. Optimal parameters**

After completing the prequel to this course, you are now beginning to think probabilistically. Outcomes of measurements follow probability distributions defined by the story of how the data came to be. When we looked at Michelson's speed of light in air measurements, we assumed that the results were Normally distributed.

**2. Histogram of Michelson's measurements**

We verified that both by looking at the PDF and

```{python}
mean = np.mean(michelson_speed_of_light)
std = np.std(michelson_speed_of_light)
samples = np.random.normal(mean, std, 10000)
# Create a Figure and an Axes with plt.subplots
fig, ax = plt.subplots()
fig.tight_layout(pad = 5)
sns.distplot(michelson_speed_of_light, hist = True, kde = True, 
             bins = 9, color = 'darkblue', 
             hist_kws = {'edgecolor':'black'},
             kde_kws = {'linewidth': 4})
#_ = ax.hist(michelson_speed_of_light, bins =  9, density = True)
#_ = ax.hist(samples, bins =  int(180/5), density = True, histtype = 'step')
_ = ax.set_xlabel('speed of light(km/s)')
_ = ax.set_ylabel('PDF')
plt.show()
```

1 Data: Michelson, 1880

**3. CDF of Michelson's measurements**

the CDF, which was more effective because there is no binning bias. To compute and plot the CDF, we needed our old friends

```{python}
x_vel_light, y_vel_light = ecdf(michelson_speed_of_light)
x_vel_light_sample, y_vel_light_sample = ecdf(samples)
# Create a Figure and an Axes with plt.subplots
fig, ax = plt.subplots()
fig.tight_layout(pad = 5)

_ = ax.plot(x_vel_light, y_vel_light, marker = '.', linestyle = 'none')
_ = ax.plot(x_vel_light_sample, y_vel_light_sample)

_ = ax.set_xlabel('speed of light (km/s)')
_ = ax.set_ylabel('CDF')
plt.show()
```
1 Data: Michelson, 1880

**4. Checking Normality of Michelson data**

Numpy and matplotlib dot pyplot, so the first step was to import them with their traditional aliases. To compute the theoretical CDF by sampling, we passed two parameters into np dot random dot normal, the mean and standard deviation. The values we chose for these parameters were in fact the mean and standard deviation we calculated directly from the data.

**5. CDF of Michelson's measurements**

The result was that the theoretical CDF overlayed beautifully with the empirical CDF. How did we know that the mean and standard deviation calculated from the data were the appropriate values for the Normal parameters? We could have chosen others.

```{python}
x_vel_light, y_vel_light = ecdf(michelson_speed_of_light)
x_vel_light_sample, y_vel_light_sample = ecdf(samples)
# Create a Figure and an Axes with plt.subplots
fig, ax = plt.subplots()
fig.tight_layout(pad = 5)

_ = ax.plot(x_vel_light, y_vel_light, marker = '.', linestyle = 'none')
_ = ax.plot(x_vel_light_sample, y_vel_light_sample)

_ = ax.set_xlabel('speed of light (km/s)')
_ = ax.set_ylabel('CDF')
plt.show()
```
1 Data: Michelson, 1880

**6. CDF with bad estimate of st. dev.**

What if the standard deviation differs by 50%? The CDFs no longer match. Or if the mean

```{python}
mean = np.mean(michelson_speed_of_light)
std = np.std(michelson_speed_of_light)
np.random.seed(42)
samples = np.random.normal(mean, std + std/2, 10000)
x_vel_light_sample, y_vel_light_sample = ecdf(samples)
# Create a Figure and an Axes with plt.subplots
fig, ax = plt.subplots()
fig.tight_layout(pad = 5)

_ = ax.plot(x_vel_light, y_vel_light, marker = '.', linestyle = 'none')
_ = ax.plot(x_vel_light_sample, y_vel_light_sample)

_ = ax.set_xlabel('speed of light (km/s)')
_ = ax.set_ylabel('CDF')
plt.show()
```
1 Data: Michelson, 1880

**7. CDF with bad estimate of mean**

varies by just point-0001%. So, if we believe that the process that generates our data gives Normally distributed results,

```{python}
mean = np.mean(michelson_speed_of_light)
std = np.std(michelson_speed_of_light)
np.random.seed(42)
samples = np.random.normal((mean + mean*0.0001), std, 10000)
x_vel_light_sample, y_vel_light_sample = ecdf(samples)
# Create a Figure and an Axes with plt.subplots
fig, ax = plt.subplots()
fig.tight_layout(pad = 5)

_ = ax.plot(x_vel_light, y_vel_light, marker = '.', linestyle = 'none')
_ = ax.plot(x_vel_light_sample, y_vel_light_sample)

_ = ax.set_xlabel('speed of light (km/s)')
_ = ax.set_ylabel('CDF')
plt.show()
```
1 Data: Michelson, 1880

**8. Optimal parameters**

the set of parameters that brings the model, in this case a Normal distribution, in closest agreement with the data uses the mean and standard deviation computed directly from the data. These are the optimal parameters. Remember though, the parameters are only optimal for

**9. Mass of MA large mouth bass**

the model you chose for your data. When your model is wrong, the optimal parameters are not really meaningful. Finding the optimal parameters is not always as easy as just computing the mean and standard deviation from the data. We will encounter this later in this chapter when we do linear regressions and we rely on built-in NumPy functions to find the optimal parameters for us. I pause to note that

```{python}
mean = np.mean(michelson_speed_of_light)
std = np.std(michelson_speed_of_light)
np.random.seed(42)
samples = np.random.normal((mean + mean*0.0001), std, 10000)
x_vel_light_sample, y_vel_light_sample = ecdf(samples)
# Create a Figure and an Axes with plt.subplots
fig, ax = plt.subplots()
fig.tight_layout(pad = 5)

_ = ax.plot(x_vel_light, y_vel_light, marker = '.', linestyle = 'none')
_ = ax.plot(x_vel_light_sample, y_vel_light_sample)

_ = ax.set_xlabel('speed of light (km/s)')
_ = ax.set_ylabel('CDF')
_ = ax.annotate("CDF for 'optimal' \nparamenters of a \nbad model", xy = ((mean + mean*0.0001)+10, 0.6), xytext = (300000.38524000003, 0.3), arrowprops = {'arrowstyle': '->', 'color': 'gray'})
plt.show()
plt.clf()
```
1 Source: Mass. Dept. of Environmental Protection

**10. Packages to do statistical inference**

there are great tools in the Python ecosystem for doing statistical inference, including by optimization, scipy dot stats and

**11. Packages to do statistical inference**

statsmodels being two good examples. In this course, however,

**12. Packages to do statistical inference**

we focus on hacker statistics because the technique is like a Swiss Army knife; the same simple principle is applicable to a wide variety of statistical problems.

1 Knife image: D
2 M Commons, CC BY
3 SA 3.0

**13. Let's practice!**

Now it's time for you to do some exercises to demonstrate how choosing optimal parameters results in best agreement between the theoretical model distribution and your data.

### **How often do we get no-hitters?**

The number of games played between each no-hitter in the modern era (1901-2015) of Major League Baseball is stored in the array `nohitter_times`.

If you assume that no-hitters are described as a Poisson process, then the time between no-hitters is Exponentially distributed. As you have seen, the Exponential distribution has a single parameter, which we will call $\tau$, the typical interval time. The value of the parameter $\tau$ that makes the exponential distribution best match the data is the mean interval time (where time is in units of number of games) between no-hitters.

Compute the value of this parameter from the data. Then, use `np.random.exponential()` to "repeat" the history of Major League Baseball by drawing inter-no-hitter times from an exponential distribution with the $\tau$ you found and plot the histogram as an approximation to the PDF.

NumPy, pandas, matlotlib.pyplot, and seaborn have been imported for you as `np`, `pd`, `plt`, and `sns`, respectively.

**Instructions**

- Seed the random number generator with `42`.
- Compute the mean time (in units of number of games) between no-hitters.
- Draw 100,000 samples from an Exponential distribution with the parameter you computed from the mean of the inter-no-hitter times.
Plot the theoretical PDF using `plt.hist()`. Remember to use keyword arguments `bins=50`, `normed=True`, and `histtype='step'`. Be sure to label your axes.
- Show your plot.

```{python}
plt.clf()
# Seed random number generator
np.random.seed(42)

# Compute mean no-hitter time: tau
tau = np.mean(nohitter_times)

# Draw out of an exponential distribution with parameter tau: inter_nohitter_time
inter_nohitter_time = np.random.exponential(tau, 100000)

# Plot the PDF and label axes
_ = plt.hist(inter_nohitter_time, density = True,
             bins = 50, histtype = 'step')
_ = plt.xlabel('Games between no-hitters')
_ = plt.ylabel('PDF')

# Show the plot
plt.show()
plt.clf()
```

We see the typical shape of the Exponential distribution, going from a maximum at 0 and decaying to the right.

### **Do the data follow our story?**

You have modeled no-hitters using an Exponential distribution. Create an ECDF of the real data. Overlay the theoretical CDF with the ECDF from the data. This helps you to verify that the Exponential distribution describes the observed data.

It may be helpful to remind yourself of the [function you created in the previous course](https://campus.datacamp.com/courses/statistical-thinking-in-python-part-1/graphical-exploratory-data-analysis?ex=12) to compute the ECDF, as well as the code you wrote to [plot it](https://campus.datacamp.com/courses/statistical-thinking-in-python-part-1/graphical-exploratory-data-analysis?ex=13).

**Instructions**

- Compute an ECDF from the actual time between no-hitters (`nohitter_times`). Use the `ecdf()` function you wrote in the prequel course.
- Create a CDF from the theoretical samples you took in the last exercise (`inter_nohitter_time`).
- Plot `x_theor` and `y_theor` as a line using `plt.plot()`. Then overlay the ECDF of the real data `x` and `y` as points. To do this, you have to specify the keyword arguments `marker = '.'` and `linestyle = 'none'` in addition to `x` and `y` inside `plt.plot()`.
- Set a 2% margin on the plot.
- Show the plot.

```{python}
# Create an ECDF from real data: x, y
x, y = ecdf(nohitter_times)

# Create a CDF from theoretical samples: x_theor, y_theor
x_theor, y_theor = ecdf(inter_nohitter_time)

# Overlay the plots
_ = plt.plot(x_theor, y_theor)
_ = plt.plot(x, y, marker = '.', linestyle = 'none')

# Margins and axis labels
_ = plt.margins(0.02)
_ = plt.xlabel('Games between no-hitters')
_ = plt.ylabel('CDF')

# Show the plot
plt.show()
plt.clf()
```

It looks like no-hitters in the modern era of Major League Baseball are Exponentially distributed. Based on the story of the Exponential distribution, this suggests that they are a random process; when a no-hitter will happen is independent of when the last no-hitter was.

## **How is this parameter optimal?**

Now sample out of an exponential distribution with $\tau$ being twice as large as the optimal $\tau$. Do it again for $\tau$ half as large. Make CDFs of these samples and overlay them with your data. You can see that they do not reproduce the data as well. Thus, the $\tau$ you computed from the mean inter-no-hitter times is optimal in that it best reproduces the data.

*Note*: In this and all subsequent exercises, the random number generator is pre-seeded for you to save you some typing.

**Instructions**

- Take `10000` samples out of an Exponential distribution with parameter  $\tau_{1/2}$= `tau/2`.
- Take `10000` samples out of an Exponential distribution with parameter  $\tau_{2}$= `2*tau`.
- Generate CDFs from these two sets of samples using your `ecdf()` function.
- Add these two CDFs as lines to your plot. This has been done for you, so hit 'Submit Answer' to view the plot!

```{python}
np.random.seed(42)
# Plot the theoretical CDFs
_ = plt.plot(x_theor, y_theor)
_ = plt.plot(x, y, marker='.', linestyle='none')
_ = plt.margins(0.02)
_ = plt.xlabel('Games between no-hitters')
_ = plt.ylabel('CDF')

# Take samples with half tau: samples_half
samples_half = np.random.exponential(tau/2, 10000)

# Take samples with double tau: samples_double
samples_double = np.random.exponential(tau*2, 10000)

# Generate CDFs from these samples
x_half, y_half = ecdf(samples_half)
x_double, y_double = ecdf(samples_double)

# Plot these CDFs as lines
_ = plt.plot(x_half, y_half)
_ = plt.plot(x_double, y_double)

# Show the plot
plt.show()
plt.clf()
```

Notice how the value of tau given by the mean matches the data best. In this way, tau is an optimal parameter.

## **Linear regression by least squares**

**1. Linear regression by least squares**

Sometimes two variables are related. You may recall from the prequel to this course that we computed the Pearson correlation coefficient between

**2. 2008 US swing state election results**

Obama's vote share in each county in swings states and the total vote count of the respective counties. The Pearson correlation coefficient is important to compute, but we might like to get a fuller understanding of how the data are related to each other. Specifically, we might suspect some underlying function gives the data its shape.

```{python}
# Create a Figure and an Axes with plt.subplots
fig, ax = plt.subplots()
fig.tight_layout(pad = 5)

_ = ax.plot(election.total_votes/900, election.dem_share, marker = '.', linestyle = 'none')

_ = ax.set_xlabel('total votes (thousands)')
_ = ax.set_ylabel('percent of vote for Obama')
_ = ax.set_ylim(0, 100)
_ = ax.set_xlim(0, 1000)
plt.show()
plt.clf()
```
1 Data retrieved from Data.gov (https://www.data.gov/)


**3. 2008 US swing state election results**

Often times a linear function is appropriate to describe the data, and this is what we will focus on in this course. The parameters of the function are

```{python}
a, b = np.polyfit(election.total_votes, election.dem_share, 1)
x = np.array([0, 1000])
y = a * x*900 + b
g = sns.relplot(x = 'total', 
                y = 'dem_share', 
                data = election,
                kind = 'scatter',
                height = 2.6)
_ = g.set(xlabel = 'total votes (thousands)',
          ylabel = 'percent of vote for Obama',
          ylim = (0, 100),
          xlim = (0, 1000))
_ = plt.plot(x, y)
plt.show()
plt.clf()
```
1 Data retrieved from Data.gov (https://www.data.gov/)

**4. 2008 US swing state election results**

the slope and intercept. The slope sets how steep the line is, and the intercept sets where the line crosses the y-axis. How do we figure out which slope and intercept best describe the data? A simple answer is that we want to choose the slope and intercept such that the data points collectively lie as close as possible to the line. 

```{python}
a, b = np.polyfit(election.total_votes, election.dem_share, 1)
x = np.array([0, 1000])
y = a * x*900 + b
g = sns.relplot(x = 'total', 
                y = 'dem_share', 
                data = election,
                kind = 'scatter',
                height = 2.6)
_ = g.set(xlabel = 'total votes (thousands)',
          ylabel = 'percent of vote for Obama',
          ylim = (0, 100),
          xlim = (0, 1000))
_ = plt.plot(x, y)
_ = plt.annotate("intercept", xy = (0, b), xytext = (400, 35), arrowprops = {'arrowstyle': '->', 'color': 'gray'})
_ = plt.annotate("slope", xy = (500, 55), xytext = (500, 70), arrowprops = {'arrowstyle': '<-', 'color': 'gray'})

plt.show()
plt.clf()
```
1 Data retrieved from Data.gov (https://www.data.gov/)

**5. 2008 US swing state election results**

This is easiest to think about by first considering one data point, say this one. The vertical distance between the data point and the line is called

```{python}
a, b = np.polyfit(election.total_votes, election.dem_share, 1)
x = np.array([0, 1000])
y = a * x*900 + b
g = sns.relplot(x = 'total', 
                y = 'dem_share', 
                data = election,
                kind = 'scatter',
                height = 2.6)
_ = g.set(xlabel = 'total votes (thousands)',
          ylabel = 'percent of vote for Obama',
          ylim = (0, 100),
          xlim = (0, 1000))
_ = plt.plot(x, y)
#_ = plt.annotate("intercept", xy = (0, b), xytext = (400, 35), arrowprops = {'arrowstyle': '->', 'color': 'gray'})
#_ = plt.annotate("slope", xy = (500, 55), xytext = (500, 70), arrowprops = {'arrowstyle': '<-', 'color': 'gray'})

plt.show()
plt.clf()
```
1 Data retrieved from Data.gov (https://www.data.gov/)

**6. Residuals**

the residual. In this case, the residual has a negative value because the data point lies below the line. Each data point has a residual associated with it.

```{python}
a, b = np.polyfit(election.total_votes, election.dem_share, 1)
x = np.array([0, 1000])
y = a * x*900 + b
g = sns.relplot(x = 'total', 
                y = 'dem_share', 
                data = election,
                kind = 'scatter',
                height = 2.6)
_ = g.set(xlabel = 'total votes (thousands)',
          ylabel = 'percent of vote for Obama',
          ylim = (0, 100),
          xlim = (0, 1000))
_ = plt.plot(x, y)
#_ = plt.annotate("intercept", xy = (0, b), xytext = (400, 35), arrowprops = {'arrowstyle': '->', 'color': 'gray'})
#_ = plt.annotate("slope", xy = (500, 55), xytext = (500, 70), arrowprops = {'arrowstyle': '<-', 'color': 'gray'})

plt.show()
plt.clf()
```
1 Data retrieved from Data.gov (https://www.data.gov/)

**7. Least squares**

We define the line that is closest to the data to be the line for which the sum of the squares of all of the residuals is minimal. This process, finding the parameters for which the sum of the squares of the residuals is minimal, is called "least squares". There are many algorithms to do this in practice.

**8. Least squares with np.polyfit()**

We will use the Numpy function polyfit, which performs least squares analysis with polynomial functions. We can use it because a linear function is a first degree polynomial. The first two arguments to this function are the x and y data. The third argument is the degree of the polynomial you wish to fit; for linear functions, we enter one. The function returns the slope and intercept of the best fit line. The slope tells us that we get about 4 more percent votes for Obama for every 100,000 additional voters in a county. Now that you know how to perform a linear regression,

```{python}
slope, intercept = np.polyfit(election.total_votes,
                                 election.dem_share, 1)
slope
```

```{python}
intercept
```

**9. Let's practice!**

let's do it with some real data in the exercises!

### **EDA of literacy/fertility data**

In the next few exercises, we will look at the correlation between female literacy and fertility (defined as the average number of children born per woman) throughout the world. For ease of analysis and interpretation, we will work with the `illiteracy` rate.

It is always a good idea to do some EDA ahead of our analysis. To this end, plot the fertility versus illiteracy and compute the Pearson correlation coefficient. The Numpy array `illiteracy` has the illiteracy rate among females for most of the world's nations. The array `fertility` has the corresponding fertility data.

Here, it may be useful to refer back to the [function you wrote in the previous course](https://campus.datacamp.com/courses/statistical-thinking-in-python-part-1/quantitative-exploratory-data-analysis?ex=15) to compute the Pearson correlation coefficient.

```{python}
def pearson_r(x, y):
  """Compute Pearson correlation coefficient between two arrays."""
  # Compute correlation matrix: corr_mat
  corr_mat = np.corrcoef(x, y)

  # Return entry [0,1]
  return corr_mat[0,1]
```

**Instructions**

- Plot `fertility` (y-axis) versus `illiteracy` (x-axis) as a scatter plot.
- Set a 2% margin.
- Compute and print the Pearson correlation coefficient between `illiteracy` and `fertility.`

```{python}
# Plot the illiteracy rate versus fertility
_ = plt.plot(illiteracy, fertility, marker = '.', linestyle='none')

# Set the margins and label axes
plt.margins(0.02)
_ = plt.xlabel('percent illiterate')
_ = plt.ylabel('fertility')

# Show the plot
plt.show()
plt.clf()

# Show the Pearson correlation coefficient
print(pearson_r(illiteracy, fertility))

```

You can see the correlation between illiteracy and fertility by eye, and by the substantial Pearson correlation coefficient of 0.8. It is difficult to resolve in the scatter plot, but there are many points around near-zero illiteracy and about 1.8 children/woman.

### **Linear regression**

We will assume that fertility is a linear function of the female illiteracy rate. That is, $f = ai + b$, where $a$ is the slope and $b$ is the intercept. We can think of the intercept as the minimal fertility rate, probably somewhere between one and two. The slope tells us how the fertility rate varies with illiteracy. We can find the best fit line using `np.polyfit()`.

Plot the data and the best fit line. Print out the slope and intercept. (Think: what are their units?)

**Instructions**

- Compute the slope and intercept of the regression line using `np.polyfit()`. Remember, `fertility` is on the y-axis and `illiteracy` on the x-axis.
- Print out the slope and intercept from the linear regression.
- To plot the best fit line, create an array `x` that consists of 0 and 100 using `np.array()`. Then, compute the theoretical values of `y` based on your regression parameters. I.e., `y = a * x + b`.
-Plot the data and the regression line on the same plot. Be sure to label your axes.
- Hit 'Submit Answer' to display your plot.

```{python}
# Plot the illiteracy rate versus fertility
_ = plt.plot(illiteracy, fertility, marker='.', linestyle='none')
plt.margins(0.02)
_ = plt.xlabel('percent illiterate')
_ = plt.ylabel('fertility')

# Perform a linear regression using np.polyfit(): a, b
a, b = np.polyfit(illiteracy,
                  fertility, 1)

# Print the results to the screen
print('slope =', a, 'children per woman / percent illiterate')
print('intercept =', b, 'children per woman')

# Make theoretical line to plot
x = np.array([0, 100])
y = a * x + b

# Add regression line to your plot
_ = plt.plot(x, y)

# Draw the plot
plt.show()
plt.clf()
```

### **How is it optimal?**

The function `np.polyfit()` that you used to get your regression parameters finds the *optimal* slope and intercept. It is optimizing the sum of the squares of the residuals, also known as RSS (for residual sum of squares). In this exercise, you will plot the function that is being optimized, the RSS, versus the slope parameter `a`. To do this, fix the intercept to be what you found in the optimization. Then, plot the RSS vs. the slope. Where is it minimal?

**Instructions**

- Specify the values of the slope to compute the RSS. Use `np.linspace()` to get `200` points in the range between `0` and `0.1`. For example, to get `100` points in the range between `0` and `0.5`, you could use `np.linspace()` like so: `np.linspace(0, 0.5, 100)`.
- Initialize an array, `rss`, to contain the RSS using `np.empty_like()` and the array you created above. The `empty_like()` function returns a new array with the same shape and type as a given array (in this case, `a_vals`).
- Write a `for` loop to compute the sum of RSS of the slope. Hint: the RSS is given by `np.sum((y_data - a * x_data - b)**2)`. The variable `b` you computed in the last exercise is already in your namespace. Here, `fertility` is the `y_data` and `illiteracy` the `x_data`.
- Plot the RSS (`rss`) versus slope (`a_vals`).
- Hit 'Submit Answer' to see the plot!

```{python}
# Specify slopes to consider: a_vals
a_vals = np.linspace(0, 0.1, 200)

# Initialize sum of square of residuals: rss
rss = np.empty_like(a_vals)

# Compute sum of square of residuals for each value of a_vals
for i, a in enumerate(a_vals):
    rss[i] = np.sum((fertility - a*illiteracy - b)**2)

# Plot the RSS
_ = plt.plot(a_vals, rss, '-')
_ = plt.xlabel('slope (children per woman / percent illiterate)')
_ = plt.ylabel('sum of square of residuals')

plt.show()
plt.clf()
```

Notice that the minimum on the plot, that is the value of the slope that gives the minimum sum of the square of the residuals, is the same value you got when performing the regression.

## **The imporatnce EDA: Anscombe's quartet**

**1. The importance of EDA: Anscombe's quartet**

In 1973, statistician Francis Anscombe published a paper that contained

**2. Anscombe's quartet**

four fictitious x-y data sets, plotted here. He uses these data sets to make an important point. That point becomes clear if we blindly go about doing parameter estimation on these data sets. First, let's look at the average x-values of the four data sets.

```{python}
a = sns.relplot(x = 'x',
                y = 'y',
                data = anscombe,
                kind = 'scatter',
                col = 'Dataset',
                col_wrap = 2,
                height = 1.7)
               
plt.show()
```

1 Data: Anscombe, The American Statistician, 1973

**3. Anscombe's quartet**

They are all the same. How about the average y-values?

```{python}
x = anscombe.x
y = anscombe.y
# Create a Figure and an array of subplots with 2 rows and 2 columns
fig, ax = plt.subplots(2, 2, sharey = True, sharex = True)

# Fit the subplots in to the figure area
#_ = fig.tight_layout(pad = 5)

# Addressing the top left Axes as index 0, 0, plot month and Seattle precipitation
_ = ax[0, 0].plot(x[0:10],
                y[0:10],
                marker = '.',
                linestyle = 'none')
_ = ax[0, 1].plot(x[11:21],
                y[11:21],
                marker = '.',
                linestyle = 'none', )
_ = ax[1, 0].plot(x[22:32],
                y[22:32],
                marker = '.',
                linestyle = 'none')
_ = ax[1, 1].plot(x[33:43],
                y[33:43],
                marker = '.',
                linestyle = 'none')

# Add vertical lines (mean of x)
_ = ax[0, 0].axvline(np.mean(anscombe.x[0:10]))
_ = ax[0, 1].axvline(np.mean(anscombe.x[11:21]))
_ = ax[1, 0].axvline(np.mean(anscombe.x[22:32]))
_ = ax[1, 1].axvline(np.mean(anscombe.x[33:43]))

# Customize the y limits
_ = ax[0, 0].set_ylim(2, 15)
_ = ax[0, 1].set_ylim(2, 15)
_ = ax[1, 0].set_ylim(2, 15)
_ = ax[1, 1].set_ylim(2, 15)

# Customize the y limits
_ = ax[0, 0].set_xlim(2, 20)
_ = ax[0, 1].set_xlim(2, 20)
_ = ax[1, 0].set_xlim(2, 20)
_ = ax[1, 1].set_xlim(2, 20)

# Customize the x-axis label
_ = ax[1, 0].set_xlabel('x')
_ = ax[1, 1].set_xlabel('x')

# Customize the y-axis label
_ = ax[0, 0].set_ylabel('y')
_ = ax[1, 0].set_ylabel('y')
plt.show()
plt.clf()
```
1 Data: Anscombe, The American Statistician, 1973

**4. Anscombe's quartet**

Again, all the same. And what if we do a linear regression on each of the data sets?

```{python}
# Create a Figure and an array of subplots with 2 rows and 2 columns
fig, ax = plt.subplots(2, 2, sharey = True, sharex = True)

# Fit the subplots in to the figure area
#_ = fig.tight_layout(pad = 5)

# Addressing the top left Axes as index 0, 0, plot month and Seattle precipitation
_ = ax[0, 0].plot(x[0:10],
                y[0:10],
                marker = '.',
                linestyle = 'none')
_ = ax[0, 1].plot(x[11:21],
                y[11:21],
                marker = '.',
                linestyle = 'none', )
_ = ax[1, 0].plot(x[22:32],
                y[22:32],
                marker = '.',
                linestyle = 'none')
_ = ax[1, 1].plot(x[33:43],
                y[33:43],
                marker = '.',
                linestyle = 'none')

# Add horizontal lines (mean of y)
_ = ax[0, 0].axhline(np.mean(anscombe.y[0:10]))
_ = ax[0, 1].axhline(np.mean(anscombe.y[11:21]))
_ = ax[1, 0].axhline(np.mean(anscombe.y[22:32]))
_ = ax[1, 1].axhline(np.mean(anscombe.y[33:43]))

# Customize the y limits
_ = ax[0, 0].set_ylim(2, 15)
_ = ax[0, 1].set_ylim(2, 15)
_ = ax[1, 0].set_ylim(2, 15)
_ = ax[1, 1].set_ylim(2, 15)

# Customize the y limits
_ = ax[0, 0].set_xlim(2, 20)
_ = ax[0, 1].set_xlim(2, 20)
_ = ax[1, 0].set_xlim(2, 20)
_ = ax[1, 1].set_xlim(2, 20)

# Customize the x-axis label
_ = ax[1, 0].set_xlabel('x')
_ = ax[1, 1].set_xlabel('x')

# Customize the y-axis label
_ = ax[0, 0].set_ylabel('y')
_ = ax[1, 0].set_ylabel('y')
plt.show()
plt.clf()
```
1 Data: Anscombe, The American Statistician, 1973

**5. Anscombe's quartet**

They all have the same line! Surely some of the fits are less optimal than others. Let's look at the sum of the squares of the residuals.

```{python}
# fit linear regression model
a0, b0 = np.polyfit(x[0:10], y[0:10], 1)
a1, b1 = np.polyfit(x[11:22], y[11:22], 1)
a2, b2 = np.polyfit(x[22:32], y[22:32], 1)
a3, b3 = np.polyfit(x[33:43], y[33:43], 1)

# predict y values
x0 = np.array([2, 20])
y0 = a0*x0 + b0
y1 = a1*x0 + b1
y2 = a2*x0 + b2
y3 = a3*x0 + b3

# Create a Figure and an array of subplots with 2 rows and 2 columns
fig, ax = plt.subplots(2, 2, sharey = True, sharex = True)

# Fit the subplots in to the figure area
#_ = fig.tight_layout(pad = 5)

# Addressing the top left Axes as index 0, 0, plot month and Seattle precipitation
_ = ax[0, 0].plot(x[0:10],
                y[0:10],
                marker = '.',
                linestyle = 'none')
_ = ax[0, 1].plot(x[11:21],
                y[11:21],
                marker = '.',
                linestyle = 'none', )
_ = ax[1, 0].plot(x[22:32],
                y[22:32],
                marker = '.',
                linestyle = 'none')
_ = ax[1, 1].plot(x[33:43],
                y[33:43],
                marker = '.',
                linestyle = 'none')

# Add predicted values
_ = ax[0, 0].plot(x0, y0)
_ = ax[0, 1].plot(x0, y1)
_ = ax[1, 0].plot(x0, y2)
_ = ax[1, 1].plot(x0, y3)

# Customize the y limits
_ = ax[0, 0].set_ylim(2, 15)
_ = ax[0, 1].set_ylim(2, 15)
_ = ax[1, 0].set_ylim(2, 15)
_ = ax[1, 1].set_ylim(2, 15)

# Customize the y limits
_ = ax[0, 0].set_xlim(2, 20)
_ = ax[0, 1].set_xlim(2, 20)
_ = ax[1, 0].set_xlim(2, 20)
_ = ax[1, 1].set_xlim(2, 20)

# Customize the x-axis label
_ = ax[1, 0].set_xlabel('x')
_ = ax[1, 1].set_xlabel('x')

# Customize the y-axis label
_ = ax[0, 0].set_ylabel('y')
_ = ax[1, 0].set_ylabel('y')
plt.show()
plt.clf()

```
1 Data: Anscombe, The American Statistician, 1973

**6. Anscombe's quartet**

Oh my, they are all basically the same as well. Of course, Anscombe constructed the data sets so that this would happen. The point he was making is very important. You already have some powerful tools for statistical inference. You can compute summary statistics and optimal parameters, including linear regression parameters, and by the end of the course, you will able to construct confidence intervals with quantify uncertainty about the parameter estimates. These are crucial skills for any data analysis, no doubt.

```{python}
# calculate the sum of squares
rss0 = np.sum((y[0:10] - a0*x[0:10] - b0)**2)
rss1 = np.sum((y[11:21] - a1*x[11:21] - b1)**2)
rss2 = np.sum((y[22:32] - a2*x[23:32] - b2)**2)
rss3 = np.sum((y[33:43] - a3*x[33:43] - b3)**2)

# Create a Figure and an array of subplots with 2 rows and 2 columns
fig, ax = plt.subplots(2, 2, sharey = True, sharex = True)

# Fit the subplots in to the figure area
#_ = fig.tight_layout(pad = 5)

# Addressing the top left Axes as index 0, 0, plot month and Seattle precipitation
_ = ax[0, 0].plot(x[0:10],
                y[0:10],
                marker = '.',
                linestyle = 'none')
_ = ax[0, 1].plot(x[11:21],
                y[11:21],
                marker = '.',
                linestyle = 'none', )
_ = ax[1, 0].plot(x[22:32],
                y[22:32],
                marker = '.',
                linestyle = 'none')
_ = ax[1, 1].plot(x[33:43],
                y[33:43],
                marker = '.',
                linestyle = 'none')

# Add predicted values
_ = ax[0, 0].plot(x0, y0)
_ = ax[0, 1].plot(x0, y1)
_ = ax[1, 0].plot(x0, y2)
_ = ax[1, 1].plot(x0, y3)

# Customize the y limits
_ = ax[0, 0].set_ylim(2, 15)
_ = ax[0, 1].set_ylim(2, 15)
_ = ax[1, 0].set_ylim(2, 15)
_ = ax[1, 1].set_ylim(2, 15)

# Customize the y limits
_ = ax[0, 0].set_xlim(2, 20)
_ = ax[0, 1].set_xlim(2, 20)
_ = ax[1, 0].set_xlim(2, 20)
_ = ax[1, 1].set_xlim(2, 20)

# Customize the x-axis label
_ = ax[1, 0].set_xlabel('x')
_ = ax[1, 1].set_xlabel('x')

# Customize the y-axis label
_ = ax[0, 0].set_ylabel('y')
_ = ax[1, 0].set_ylabel('y')
''.join(["sum sq. rsid. = ", str(rss0)])
# Annotate the sum of squares
_ = ax[0, 0].annotate(''.join(["sum sq. rsid. = ", str(round(rss0, 1))]), xy = (9, 4), xytext = (8, 4))
_ = ax[0, 1].annotate(''.join(["sum sq. rsid. = ", str(round(rss1, 1))]), xy = (9, 4), xytext = (8, 4))
_ = ax[1, 0].annotate(''.join(["sum sq. rsid. = ", str(round(rss2, 1))]), xy = (9, 4), xytext = (8, 4))
_ = ax[1, 1].annotate(''.join(["sum sq. rsid. = ", str(round(rss3, 1))]), xy = (9, 4), xytext = (8, 4))

plt.show()
plt.clf()
```
1 Data: Anscombe, The American Statistician, 1973

**7. Look before you leap!**

But look before you leap! This is a powerful reminder to do some graphic exploratory data analysis before you start computing and making judgments about your data. For example,

**8. Anscombe's quartet**

this data set might be well modeled with a line, and the regression parameters will be meaningful. The same is true of

1 Data: Anscombe, The American Statistician, 1973

**9. Anscombe's quartet**

this data set, but the outlier throws off the slope and intercept. After doing EDA, you should look into what is causing that outlier.

1 Data: Anscombe, The American Statistician, 1973

**10. Anscombe's quartet**

This data set might also have a linear relationship between x and y, but from the plot, you can conclude that you should try to acquire more data for intermediate x values to make sure that it does.

1 Data: Anscombe, The American Statistician, 1973

**11. Anscombe's quartet**

And this data set is definitely not linear, and you need to choose another model. Explore your data first. I'll let you prove to yourself

1 Data: Anscombe, The American Statistician, 1973

**12. Let's practice!**

that these data sets give the same regression parameters. It will be good practice, and seeing is believing!

### **The importance of EDA**

Why should exploratory data analysis be the first step in an analysis of data (after getting your data imported and cleaned, of course)?

**Possible Answers**

1. You can be protected from misinterpretation of the type demonstrated by Anscombe's quartet.

2. EDA provides a good starting point for planning the rest of your analysis.

3. EDA is not really any more difficult than any of the subsequent analysis, so there is no excuse for not exploring the data.

4. All of these reasons!

Answer: 4

### **Linear regression on appropriate Anscombe data**

For practice, perform a linear regression on the data set from Anscombe's quartet that is most reasonably interpreted with linear regression.

**Instructions**

- Compute the parameters for the slope and intercept using `np.polyfit()`. The Anscombe data are stored in the arrays `x` and `y`.
- Print the slope `a` and intercept `b`.
- Generate theoretical $x$ and $y$ data from the linear regression. Your $x$ array, which you can create with `np.array()`, should consist of `3` and `15`. To generate the $y$ data, multiply the slope by `x_theor` and add the intercept.
- Plot the Anscombe data as a scatter plot and then plot the theoretical line. Remember to include the `marker='.'` and `linestyle='none'` keyword arguments in addition to `x` and `y` when to plot the Anscombe data as a scatter plot. You do not need these arguments when plotting the theoretical line.
- Hit 'Submit Answer' to see the plot!

```{python}
x = x[0:10]
y = y[0:10]

_ = plt.tight_layout(pad = 2)

# Perform linear regression: a, b
a, b = np.polyfit(x, y, 1)

# Print the slope and intercept
print(a, b)

# Generate theoretical x and y data: x_theor, y_theor
x_theor = np.array([3, 15])
y_theor = a * x_theor + b

# Plot the Anscombe data and theoretical line
_ = plt.plot(x, y, marker = '.', linestyle = 'none')
_ = plt.plot(x_theor, y_theor)

# Label the axes
_ = plt.xlabel('x')
_ = plt.ylabel('y')

# Show the plot
plt.show()
plt.clf()
```

### **Linear regression on all Anscombe data**

Now, to verify that all four of the Anscombe data sets have the same slope and intercept from a linear regression, you will compute the slope and intercept for each set. The data are stored in lists; `anscombe_x = [x1, x2, x3, x4]` and `anscombe_y = [y1, y2, y3, y4]`, where, for example, `x2` and `y2` are the $x$ and $y$ values for the second Anscombe data set.

```{python, echo = False}
x1 = x[0:10]
x2 = x[11:22]
x3 = x[23:32]
x4 = x[33:43]
y1 = y[0:10]
y2 = y[11:22]
y3 = y[23:32]
y4 = y[33:43]
anscombe_x = [x1, x2, x3, x4]
anscombe_y = [y1, y2, y3, y4]
```

**Instructions**

- Write a `for` loop to do the following for each Anscombe data set.
  - Compute the slope and intercept.
  - Print the slope and intercept.

```{python}
# Iterate through x,y pairs
for x, y in zip(anscombe_x, anscombe_y):
    # Compute the slope and intercept: a, b
    a, b = np.polyfit(x, y, 1)
    # Print the result
    print('slope:', a, 'intercept:', b)

```

Indeed, they all have the same slope and intercept.