---
title: "02 -Interacting with APIs to import data from web"
output: 
  html_notebook:
    toc: true
    toc_float: false
    toc_depth: 4
editor_options: 
  chunk_output_type: inline
---

```{python setup}
import pandas as pd
import numpy as np
```

## **Introduction to APIs and JSONs**

**1. Introduction to APIs and JSONs**

In this chapter, you'll explore pulling data from the web even further by

**2. APIs**

learning how to interact with APIs, or Application Programming Interfaces. An API is a set of protocols and routines for building and interacting with software applications. In particular, you'll learn how to use the Open Movie Database API and, in the next chapter,

**3. APIs**
the Twitter API to pull data from both applications, while learning about API interaction best practices. A standard form for transferring data through APIs is

**4. JSONs**

the JSON file format, so in this video, we'll focus our attention squarely on these. Then we'll move onto actually getting data from APIs. JSON is an acronym that is short for JavaScript Object Notation. It is a file format that arose out of a growing need for real-time server-to-browser communication that wouldn't necessarily rely on Flash or Java and was first specified and also popularized by Douglas Crockford, an American programmer and entrepreneur. One of the cool things about JSONs is that they're human readable, that is, they can naturally be read by humans unlike, for example, pickled files, as we saw in the previous course. As they're human readable, let's check one out!

**5. JSONs**

Here you see a JSON from the OMDB OR Open Movie Database API. In particular, this is JSON containing information about the movie Snakes on a Plane. First notice that the JSON consists of name-value pairs separated by commas. This will remind you of the key-value pairs in a Python dictionary! We'll see in a minute that, for this reason, when loading JSONs into Python, it is natural to store them in a dict. The keys in JSONs will always be strings enclosed in quotation marks. The values can be strings, integers, arrays or even objects. Such an object can even be a JSON and then you have nested JSONs but we won't go further into these here. In this case of the Snakes on a Plane JSON, all the values are strings and we can see this from the quotation marks.

**6. JSONs**

The value corresponding to the key 'Title' is the title of the movie as a string: Snakes on a Plane.

**7. JSONs**

The value corresponding to the key 'Year' is the year of release as a string: 2006 and so on. There's the rating, the runtime, director, writers, plot, language and much more! You'll soon learn how to use the OMDB API and Python to automate retrieval of such data, but first you'll figure out how to load JSONs from a local directory.

**8. Loading JSONs in Python**

Lets say that I had the JSON stored in my working directory as 'snakes dot json'. To load the JSON into my Python environment, I would first import the package json and then open a connection to the file and use the function json dot load to load the JSON. If I then check the datatype of json_data by executing type(json_data), I see that Python cleverly imported the JSON as a dictionary!

**9. Exploring JSONs in Python**

To print the key-value pairs to the console, I can then iterate over the key-value pairs using a for loop. Now it's your turn to test your JSON skills

**10. Let's practice!**

so get coding!

### **Pop quiz: What exactly is a JSON?**

Which of the following is NOT true of the JSON file format?

**Possible Answers**

1. JSONs consist of key-value pairs.

2. JSONs are human-readable.

3. The JSON file format arose out of a growing need for real-time server-to-browser communication.

4. The function `json.load()` will load the JSON into Python as a `list`.

5. The function `json.load()` will load the JSON into Python as a `dictionary`.

Answer:

### **Loading and exploring a JSON**

Now that you know what a JSON is, you'll load one into your Python environment and explore it yourself. Here, you'll load the JSON `'a_movie.json'` into the variable `json_data`, which will be a dictionary. You'll then explore the JSON contents by printing the key-value pairs of `json_data` to the shell.

**Instructions**

- Load the JSON `'a_movie.json'` into the variable `json_data` within the context provided by the `with` statement. To do so, use the function `json.load()` within the context manager.
- Use a `for` loop to print all key-value pairs in the dictionary `json_data`. Recall that you can access a value in a dictionary using the syntax: `dictionary[key]`.

```{python}
# Load JSON: json_data
with open("a_movie.json") as json_file:
    ____

# Print each key-value pair in json_data
for k in json_data.keys():
    print(k + ': ', ____)
```

### **Pop quiz: Exploring your JSON**

Load the JSON `'a_movie.json'` into a variable, which will be a dictionary. Do so by copying, pasting and executing the following code in the IPython Shell:

```{python}
import json
with open("a_movie.json") as json_file:
    json_data = json.load(json_file)
```

Print the values corresponding to the keys `'Title'` and `'Year'` and answer the following question about the movie that the JSON describes:

Which of the following statements is true of the movie in question?

**Possible Answers**

1. The title is 'Kung Fu Panda' and the year is 2010.

2. The title is 'Kung Fu Panda' and the year is 2008.

3. The title is 'The Social Network' and the year is 2010.

4. The title is 'The Social Network' and the year is 2008.

Answer:

## **APIs and interecting with the word wide web**

**1. APIs and interacting with the world wide web**

Congrats on making it through your crash course in JSONs! JSONs are everywhere and one of the main motivating reasons for getting to know how to work with them as a Data Scientist is that much of the data that you'll get from APIs are packaged as JSONs.

**2. Herein, you’ll learn**

In this video, you'll learn what APIs are, why they are so important, and see a number of illustrative examples. In the subsequent interactive exercises, you'll gain valuable practice connecting to a variety of APIs, pulling and parsing data from them.

**3. What is an API?**

So what is an API and why are they so important? Simply put, an API is a set of protocols and routines for building and interacting with software applications. Another way to think of it is that an API is a bunch of code that allows two software programs to communicate with each other. For example, if you wanted to stream twitter data by writing some Python code, you would use the Twitter API. If you wanted to automate pulling and processing information

**4. What is an API?**

from Wikipedia in your programming language of choice, you could do so using the Wikipedia API.

**5. APIs are everywhere**

Using such APIs have now become standard ways of interacting with such applications. Twitter has an API that is used by marketing companies and social scientists engaged in research concerning social networks.

**6. APIs are everywhere**

Uber,

**7. APIs are everywhere**

Facebook and

**8. APIs are everywhere**

Instagram all have APIs. Now let's figure out how to connect to an API and how to pull data from it.

**9. Connecting to an API in Python**

In this example, we'll pull movie data from the Open Movie Database, or OMDB, API. Once again, you'll use the ever-elegant requests library. You import requests and assign the URL of interest to the variable url. You then package and send the request to the URL, which describes your API query, and catch the response in one line of code. Thanks again, requests package! Another really cool aspect of the requests package is that the Response objects, such as r, have an associate method json, which is a built-in JSON decoder for when we're dealing with JSON data. This returns a dictionary and we can then print all the key-value pairs to check out what we pulled from the OMBD API!

**10. What was that URL?**

Now the last thing to discuss is how the URL we used actually pulled data from the API. To do so, lets break it up into chunks. The http signifies that we're making an HTTP request, the 'www dot omdb dot api' that we're querying the OMDB API, then there's the "?t equals hackers" which is the really interesting part and something we haven't discussed yet in this course. This string that begins with a question mark is called a Query String. Query Strings are parts of URLs that do not necessarily fit into conventional a hierarchical path structure. What follows the question mark in the query string is the query we are making to the OMBD API. The query we just made was simple : querying 't equals hackers' asked the API to return the data about the movie with the title Hackers. The 't' in the query stood for title.

**11. OMDb API**

We knew that this was how to perform such a query from the documentation on the OMDB API's homepage. Under "Usage" here, they state explicitly that 'Send all data requests to: http:// www dot omdbapi dot com /?'.

**12. OMDb API**

They also have a query string parameters table that shows how to query a particular title or a particular movie ID.

**13. It’s a regular URL!**

It is also worth mentioning that there is nothing special about this URL and so you can also navigate to it in your browser of choice. It will generally look like this. I like to use a Chrome extension called JSON formatter to make it a bit prettier. Alright. Now you know all about APIs and have a basic practical understanding of how to query them,

**14. Let's practice!**

lets get you writing some Python to extract some data from a number of APIs! Happy coding!

### **Pop quiz: What's an API?
Which of the following statements about APIs is NOT true?

Answer the question
50XP
Possible Answers

1. An API is a set of protocols and routines for building and interacting with software applications.

2. API is an acronym and is short for Application Program  interface.

3. It is common to pull data from APIs in the JSON file  format.

4. All APIs transmit data only in the JSON file format.

5. An API is a bunch of code that allows two software programs to communicate with each other.

Answer:

### **API requests**

Now it's your turn to pull some movie data down from the Open Movie Database (OMDB) using their API. The movie you'll query the API about is The Social Network. Recall that, in the video, to query the API about the movie Hackers, Hugo's query string was `'http://www.omdbapi.com/?t=hackers'`  and had a single argument `t=hackers`.

Note: recently, OMDB has changed their API: you now also have to specify an API key. This means you'll have to add another argument to the URL: `apikey=72bc447a`.

**Instructions**

- Import the requests package.
- Assign to the variable url the URL of interest in order to query `'http://www.omdbapi.com'` for the data corresponding to the movie The Social Network. The query string should have two arguments: `apikey=72bc447a` and `t=the+social+network`. You can combine them as follows: `apikey=72bc447a&t=the+social+network`.
- Print the text of the response object `r` by using its text attribute and passing the result to the `print()` function.

```{python}
# Import requests package


# Assign URL to variable: url


# Package the request, send the request and catch the response: r
r = requests.get(url)

# Print the text of the response


```

### **JSON–from the web to Python**

Wow, congrats! You've just queried your first API programmatically in Python and printed the text of the response to the shell. However, as you know, your response is actually a JSON, so you can do one step better and decode the JSON. You can then print the key-value pairs of the resulting dictionary. That's what you're going to do now!

**Instructions**

- Pass the variable `url` to the `requests.get()` function in order to send the relevant request and catch the response, assigning the resultant response message to the variable `r`.
- Apply the `json()` method to the response object `r` and store the resulting dictionary in the variable `json_data`.
- Hit Submit Answer to print the key-value pairs of the dictionary `json_data` to the shell.

```{python}
# Import package
import requests

# Assign URL to variable: url
url = 'http://www.omdbapi.com/?apikey=72bc447a&t=social+network'

# Package the request, send the request and catch the response: r


# Decode the JSON data into a dictionary: json_data


# Print each key-value pair in json_data
for k in json_data.keys():
    print(k + ': ', json_data[k])

```

### **Checking out the Wikipedia API**

You're doing so well and having so much fun that we're going to throw one more API at you: the Wikipedia API (documented [here](https://www.mediawiki.org/wiki/API:Main_page)). You'll figure out how to find and extract information from the Wikipedia page for *Pizza*. What gets a bit wild here is that your query will return *nested* JSONs, that is, JSONs with JSONs, but Python can handle that because it will translate them into dictionaries within dictionaries.

The URL that requests the relevant query from the Wikipedia API is

`https://en.wikipedia.org/w/api.php?action=query&prop=extracts&format=json&exintro=&titles=pizza`

**Instructions**

- Assign the relevant URL to the variable `url`.
- Apply the `json()` method to the response object `r` and store the resulting dictionary in the variable `json_data`.
- The variable `pizza_extract` holds the HTML of an extract from Wikipedia's *Pizza* page as a string; use the function `print()` to print this string to the shell.

```{python}
# Import package
import requests

# Assign URL to variable: url


# Package the request, send the request and catch the response: r
r = requests.get(url)

# Decode the JSON data into a dictionary: json_data


# Print the Wikipedia page extract
pizza_extract = json_data['query']['pages']['24768']['extract']
____

```

