---
title: "03 - Time Zones and Daylight Saving"
output: 
  html_notebook:
    toc: true
    toc_float: false
    toc_depth: 4
editor_options: 
  chunk_output_type: inline
---

```{python setup}
import pandas as pd
import numpy as np
```


## **UTC offsets**

**1. UTC offsets**

Sometimes, you really need to know exactly when something happened. Up until now, the datetime objects you have worked with are what is called "naive", and can't be compared across different parts of the world. They don't know anything about their time zone.

**2. Time zones**

Why does this matter? Before time zones, each town or city set its clock so that noon was directly overhead.

**3. Time zones**

Another city 100 miles away would also set their clocks to be noon when the sun was overhead.

**4. Time zones**

But this meant that these two cities had clocks that were different, by maybe 15 or 20 minutes. When people moved by foot or horseback, this wasn't a problem.

**5. Time zones**

Then railroads, and later telegraphs, came into existence. Now you could move or communicate with someone 100 or even 1000 miles away fast enough that time had to be consistent.

**6. Time zones**

Governments solved this problem by declaring that all clocks within a wide area would agree on the hour, even if some were ahead or behind of their solar time. The United States, for example, has 4 major time zones, plus one for Alaska and another for Hawaii. Our bike data was collected in Washington, D.C., which observes Eastern time.

**7. UTC**

But since we're not using the sun anymore, how do we know how to set the clock? Because the United Kingdom was the first to standardize its time, everyone in the world sets their clocks relative to the original historical UK standard. This standard time is called UTC. Because all clocks are set relative to UTC, we can compare time around the world. Generally, clocks west of the UK are set earlier than UTC, and clocks east of the UK are set later than UTC. For example, the eastern United States is typically UTC minus 5 hours, while India is typically UTC plus 5 hours 30 minutes.

**8. UTC**

Let's see this in code. As before, you import datetime and timedelta. Now you also import timezone. This will let you specify what timezone the clock was in when our data was recorded.

**9. UTC**

We create a timezone object, which accepts a timedelta that explains how to translate your datetime into UTC. In this case, since the clock that measured our bicycle data set was five hours behind UTC, we create ET to be at UTC-5. We can specify what time zone the clock was in when the last ride started in our data set. The clock that recorded the ride was 5 hours behind UTC. Now if you print it, your datetime includes the UTC offset.

**10. UTC**

Making a datetime "aware" of its timezone means you can ask Python new questions. For example, suppose you want to know what the date and time would have been if the clock had been set to India Standard Time instead. First, create a new timezone object set to UTC plus 5 hours 30 minutes. Now use the astimezone() method to ask Python to create a new datetime object corresponding to the same moment, but adjusted to a different time zone. In this case, because clocks in India would have been set 10.5 hours ahead of clocks on the eastern US, the last ride would have taken place on December 31, at 1 hour, 39 minutes, and 3 seconds past midnight local time. Same moment, different clock.

**11. Adjusting timezone vs changing tzinfo**

Finally, there is an important difference between adjusting timezones and changing the tzinfo directly. You can set the tzinfo directly, using the replace() method. Here we've set the tzinfo to be timezone.utc, a convenient object with zero UTC offset. The clock stays the same, but the UTC offset has shifted. Or, just like before, you can call the astimezone() method. Now if we adjust into UTC with astimezone(timezone.utc), we change both the UTC offset and the clock itself.

**12. UTC Offsets**
Now that you have learned about UTC offsets, which allow us to compare times around the world, it's time to practice using them!

### **Creating timezone aware datetimes**

In this exercise, you will practice setting timezones manually.

**Instructions**

1.
- Import `timezone`.
- Set the `tzinfo` to UTC, without using `timedelta`.
2.
- Set `pst` to be a timezone set for UTC-8.
- Set `dt`'s timezone to be `pst`.
3.
- Set `tz` to be a timezone set for UTC+11.
- Set `dt`'s timezone to be `tz`.

```{python}
# Import datetime, timezone
from datetime import datetime, ____

# October 1, 2017 at 15:26:26, UTC
dt = datetime(2017, 10, 1, 15, 26, 26, tzinfo=____)

# Print results
print(dt.isoformat())
```

### **Setting timezones**

Now that you have the hang of setting timezones one at a time, let's look at setting them for the first ten trips that W20529 took.

`timezone` and `timedelta` have already been imported. Make the change using `.replace()`

**Instructions**

- Create `edt`, a `timezone` object whose UTC offset is -4 hours.
- Within the `for` loop:
- Set the `tzinfo` for `trip['start']`.
- Set the `tzinfo` for `trip['end']`.

```{python}
# Create a timezone object corresponding to UTC-4
edt = ____

# Loop over trips, updating the start and end datetimes to be in UTC-4
for trip in onebike_datetimes[:10]:
  # Update trip['start'] and trip['end']
  trip['start'] = trip['start'].____
  trip['end'] = trip['end'].____
```

### **What time did the bike leave in UTC?**

Having set the timezone for the first ten rides that W20529 took, let's see what time the bike left in UTC. We've already loaded the results of the previous exercise into memory.

**Instructions**

Within the `for` loop, move `dt` to be in UTC. Use `timezone.utc` as a convenient shortcut for UTC.

```{python}
# Loop over the trips
for trip in onebike_datetimes[:10]:
  # Pull out the start
  dt = trip['start']
  # Move dt to be in UTC
  dt = dt.____(____)
  
  # Print the start time in UTC
  print('Original:', trip['start'], '| UTC:', dt.isoformat())
```

## **Time zone database**

**1. Time zone database**

Now that you understand how UTC offsets work, it's time to talk about how you use timezones in practice.

**2. Time zone database**

This is a picture of all of the different time zones in the world, as of 2017. They cut across countries, and within countries, and sometimes one is even totally surrounded by another one. How could you possibly know all of these when you need to align your data to UTC? Do you need to look up the offset for each one in some big spreadsheet somewhere? Can't a computer help with this?

**3. Time zone database**

Thankfully, yes. There is a database called tz, updated 3-4 times a year as timezone rules change. This database is used by computer programs across many programming languages. Because timezone information changes so quickly, it doesn't make sense to bundle it directly into Python. Instead, you will use a package called dateutil.

**4. Time zone database**

Let's start by making a timezone object that corresponds to the eastern United States, where our bicycle data comes from. Within tz, time zones are defined first by the continent they are on, and then by the nearest major city. For example, the time zone used on the eastern seaboard of the United States is 'America/New York'. We fetch this timezone by calling tz.gettz(), and passing 'America/New York' as the string.

**5. Time zone database**

Here are a few more examples: 'America/Mexico_City'. 'Europe/London'. 'Africa/Accra'.

**6. Time zone database**

Let's look at our last ride again. Instead of specifying the UTC offset yourself, you pass the timezone you got from tz. Look at the result, and you can see that it's got the right UTC offset.

**7. Time zone database**

Even more excitingly, this same object will adjust the UTC offset depending on the date and time. If we call datetime() with the time of our first ride, and pass in the same timezone info, we see that it gives us a different UTC offset. We will discuss daylight savings time in the next lesson, but suffice to say that in some places the clocks change twice a year. Instead of having to look up when these things change, we just ask the timezone database to know for us. tz includes rules for UTC offsets going all the way back to the late 1960s, and sometimes earlier. If you have data stretching over a long period of time, and you really care about getting the exact hours and minutes correct, you can use tz to put all of your date and timestamps on to a common scale.

**8. Time zone database**

Now that you have a basic understanding of using the tz class from dateutil, it's time to practice some examples!

### **Putting the bike trips into the right time zone**

Instead of setting the timezones for W20529 by hand, let's assign them to their IANA timezone: `'America/New_York'`. Since we know their political jurisdiction, we don't need to look up their UTC offset. Python will do that for us.

**Instructions**

- Import `tz` from `dateutil`.
- Assign `et` to be the timezone `'America/New_York'`.
- Within the `for` loop, set `start` and `end` to have `et` as their timezone (use `.replace()`).

```{python}
# Import tz
from ____ import ____

# Create a timezone object for Eastern Time
et = tz.____('America/New_York')

# Loop over trips, updating the datetimes to be in Eastern Time
for trip in onebike_datetimes[:10]:
  # Update trip['start'] and trip['end']
  trip['start'] = trip['start'].____
  trip['end'] = trip['end'].____
```

### **What time did the bike leave? (Global edition)**

When you need to move a `datetime` from one timezone into another, use `.astimezone()` and `tz`. Often you will be moving things into UTC, but for fun let's try moving things from `'America/New_York'` into a few different time zones.

**Instructions**

1.
- Set `uk` to be the timezone for the UK: `'Europe/London'`.
- Change local to be in the `uk` timezone and assign it to `notlocal`.
2.
- Set `ist` to be the timezone for India: `'Asia/Kolkata'`.
- Change `local` to be in the `ist` timezone and assign it to `notlocal`.
3.
- Set `sm` to be the timezone for Samoa: `'Pacific/Apia'`.
- Change `local` to be in the `sm` timezone and assign it to `notlocal`.

```{python}
# Create the timezone object
uk = ____

# Pull out the start of the first trip
local = onebike_datetimes[0]['start']

# What time was it in the UK?
notlocal = local.____(____)

# Print them out and see the difference
print(local.isoformat())
print(notlocal.isoformat())
```

## **Starting daylight saving time**

**1. Starting Daylight Saving Time**

Some places change their clocks twice a year to create longer summer evenings. This practice is called daylight saving time, but it would better be called daylight shifting time. In some countries it is called "summer time". Dealing with daylight saving time can be one of the most fiendish challenges in dealing with dates and times. To keep things simple, let's start with the situation where the clocks move forward in the spring. In the next lesson, we'll discuss handling the opposite case, when the clocks move back in the fall.

**2. Start of Daylight Saving Time**

Let's look at an example. On March 12, 2017, in Washington, D.C., the clock jumped straight from 1:59 am to 3 am. The clock "springs forward". It never officially struck 2 am anywhere on the East Coast of the United States that day.

**3. Start of Daylight Saving Time**

Just like before, to make our clock in Washington, D.C. comparable to clocks in other places, we need to represent it with a UTC offset. Only now the UTC offset is going to change. On this date, at 1 AM in Washington, D.C., we were in Eastern Standard Time. It was 6 AM UTC, a five-hour difference. At 3 AM in Washington, D.C., we were in Eastern Daylight Time. It was 7 AM UTC, a four-hour difference.

**4. Start of Daylight Saving Time**

Let's see the same thing in code. To be as clear as possible, let's create the UTC offsets by hand for now instead of using dateutil.tz. We start by creating a datetime object, spring_ahead_159am, for March 12th, at 1:59:59, without any timezone information. We print the results out with isoformat() to check that we have the time right, and we make another object for spring_ahead_3am. We subtract the two datetime objects and ask how much time has elapsed by calling total_seconds(). As expected, they're an hour and one second apart.

**5. Start of Daylight Saving Time**

As before, to fix problems with comparing datetimes we start by creating timezone objects. We define Eastern Standard Time, or EST, using the timezone constructor. We set the offset to -5 hours. Similarly, we define Eastern Daylight Time, or EDT, with an offset of -4 hours.

**6. Start of Daylight Saving Time**

We assign our first timestamp, at 1:59 am to be in EST. When we call isoformat(), we see it has the correct offset. We assign our second timestamp, at 3:00 am, to be in EDT, and again check the output with isoformat(). When we subtract the two datetime objects, we see correctly that one second has elapsed. Putting things in terms of UTC once again allowed us to make proper comparisons.

**7. Start of Daylight Saving Time**

But how do we know when the cutoff is without looking it up ourselves? dateutil to the rescue again. Just like before when it saved us from having to define timezones by hand, dateutil saves us from having to know daylight savings rules. We create a timezone object by calling tz.gettz() and pass our timezone description string. Recall that since Washington, D.C. is in the America/New_York time zone, that's what we use. Once again we create a datetime corresponding to 1:59 am on the day that the east coast of the US springs forward. This time though, we set the tzinfo to eastern time. Similarly, we create a datetime set to 3 am on March 12th, and when we set tzinfo to be eastern time, dateutil figures out for us that it should be in EDT.

**8. Daylight Saving**

In this lesson, we covered "spring ahead". Let's try some examples of working with datetimes that handle a switch into daylight saving time.

### **How many hours elapsed around daylight saving?**

Since our bike data takes place in the fall, you'll have to do something else to learn about the start of daylight savings time.

Let's look at March 12, 2017, in the Eastern United States, when Daylight Saving kicked in at 2 AM.

If you create a `datetime` for midnight that night, and add 6 hours to it, how much time will have elapsed?

**Instructions**

1.
- You already have a `datetime` called `start`, set for March 12, 2017 at midnight, set to the timezone `'America/New_York'`.
- Add six hours to `start` and assign it to `end`. Look at the UTC offset for the two results.
2. 
- 

```{python}
# Import datetime, timedelta, tz, timezone
from datetime import datetime, timedelta, timezone
from dateutil import tz

# Start on March 12, 2017, midnight, then add 6 hours
start = datetime(2017, 3, 12, tzinfo = tz.gettz('America/New_York'))
end = start + ____(____)
print(start.isoformat() + " to " + end.isoformat())
```

### **March 29, throughout a decade**

Daylight Saving rules are complicated: they're different in different places, they change over time, and they usually start on a Sunday (and so they move around the calendar).

For example, in the United Kingdom, as of the time this lesson was written, Daylight Saving begins on the last Sunday in March. Let's look at the UTC offset for March 29, at midnight, for the years 2000 to 2010.

**Instructions**

- Using `tz`, set the timezone for `dt` to be `'Europe/London'`.
- Within the `for` loop:
- Use the `.replace()` method to change the year for `dt` to be `y`.
- Call `.isoformat()` on the result to observe the results.

```{python}
# Import datetime and tz
from datetime import datetime
from dateutil import tz

# Create starting date
dt = datetime(2000, 3, 29, tzinfo = ____)

# Loop over the dates, replacing the year, and print the ISO timestamp
for y in range(2000, 2011):
  print(dt.____(year=____).____())
```

## **Ending daylight saving time**

**1. Ending Daylight Saving Time**

In the previous lesson, we discussed how to handle when the clock "springs ahead" and we enter daylight saving. In the fall, when the clocks are reset back to standard time, an interesting wrinkle occurs. In this lesson, we'll finish our discussion of daylight saving time by showing what happens when we "fall back", and also talk about how to unambiguously handle events which bridge a daylight savings jump.

**2. Ending Daylight Saving Time**

Let's look back at our example in Washington, D.C., on the day that daylight saving time ended. On November 5th, 2017, at 2 AM the clocks jumped back an hour. That means there were two 1 AMs! We've represented this by "folding" over our timeline to show the repeat.

**3. Ending Daylight Saving Time**

As before, in order to make sense of this situation, we need to map everything back to UTC. The first 1 AM maps to 5 AM UTC. This is the minus 4 hour UTC offset for Eastern Daylight Time we discussed in the previous lesson. At 1:59:59 local time, we're at 5:59:59 UTC. The next moment, our local clock jumps back, but since time has not actually gone backward, the clock continues to tick in UTC. We switch to a UTC offset of minus 5 hours (colored in blue), and the second 1 AM corresponds to 6 AM UTC.

**4. Ending Daylight Saving Time**

First, let's make a tzinfo object corresponding to our bike data's timezone. We make a datetime for November 5th and 1 am. Let's check and see if this time is ambiguous, meaning we need to tell it apart somehow. We call tz.datetime_ambiguous(), and see that, yes, this is a time which could occur at two different UTC moments in this timezone. Now we create a second datetime, with the same date and time. This time, we call tz.enfold(), which takes the argument of the datetime we want to mark. enfold says, this datetime belongs to the *second* time the wall clock struck 1 AM this day, and not the first.

**5. Ending Daylight Saving Time**

The thing is, enfold by itself doesn't change any of the behavior of a datetime. You can see here that Python doesn't take it into account when doing datetime arithmetic. Fold is just a placeholder, and it's up to further parts of the program to pay attention to fold and do something with it. What are we going to do?! We need to convert to UTC, which is unambiguous. When we really want to make sure that everything is accounted for, putting everything into UTC is the way to do it. Now when we ask Python to take the difference, we see that it correctly tells us these two timestamps are an hour apart. In general, whenever we really want to be sure of the duration between events that might cross a daylight saving boundary, we need to do our math in UTC.

**6. Ending Daylight Saving Time**

We've covered how to handle springing forward and falling back, both with hand-coded UTC offsets and with dateutil. Python often tries to be helpful by glossing over daylight saving time difference, and oftentimes that's what you want. However, when you do care about it, use dateutil to set the timezone information correctly and then switch into UTC for the most accurate comparisons between events.

### **Finding ambiguous datetimes**

At the end of lesson 2, we saw something anomalous in our bike trip duration data. Let's see if we can identify what the problem might be.

The data is loaded as `onebike_datetimes`, and tz has already been imported from `dateutil`.

**Instructions**

- Loop over the trips in `onebike_datetimes`:
  - Print any rides whose start is ambiguous.
  - Print any rides whose end is ambiguous.

```{python}
# Loop over trips
for trip in onebike_datetimes:
  # Rides with ambiguous start
  if tz.____(____):
    print("Ambiguous start at " + str(trip['start']))
  # Rides with ambiguous end
  if tz.____(____):
    print("Ambiguous end at " + str(trip['end']))
```

### **Cleaning daylight saving data with fold**

As we've just discovered, there is a ride in our data set which is being messed up by a Daylight Savings shift. Let's clean up the data set so we actually have a correct minimum ride length. We can use the fact that we know the end of the ride happened after the beginning to fix up the duration messed up by the shift out of Daylight Savings.

Since Python does not handle `tz.enfold()` when doing arithmetic, we must put our datetime objects into UTC, where ambiguities have been resolved.

`onebike_datetimes` is already loaded and in the right timezone. `tz` and `timezone` have been imported. Use `tz.UTC` for the timezone.

**Instructions**

- Complete the `if` statement to be true only when a ride's `start` comes after its `end`.
- When `start` is after `end`, call `tz.enfold()` on the end so you know it refers to the one after the daylight savings time change.
- After the `if` statement, convert the start and end to UTC so you can make a proper comparison.

```{python}
trip_durations = []
for trip in onebike_datetimes:
  # When the start is later than the end, set the fold to be 1
  if ____ > ____:
    trip['end'] = tz.____(trip['end'])
  # Convert to UTC
  start = trip['start'].____
  end = trip['end'].____

  # Subtract the difference
  trip_length_seconds = (end-start).total_seconds()
  trip_durations.append(trip_length_seconds)

# Take the shortest trip duration
print("Shortest trip: " + str(min(trip_durations)))
```

