---
title: "02 - Visualizing two quantitatie variables"
output: 
  html_notebook:
    toc: true
    toc_float: false
    toc_depth: 4
    code_folding: hide
---

```{python setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

countries = pd.read_csv('/home/cla/Documentos/Vitor/DataCamp/Data-Scientist-with-Python/Datasets/countries-of-the-world.csv')
countries = countries.replace(to_replace = ',', value = '.', regex = True)
countries['Phones (per 1000)'] = countries['Phones (per 1000)'].astype(float, errors = 'raise')
countries['Literacy (%)'] = countries['Literacy (%)'].astype(float, errors = 'raise')
gdp = list(countries['GDP ($ per capita)'])
phones = list(countries['Phones (per 1000)'])
percent_literate = list(countries['Literacy (%)'])
region = list(countries.Region)
csv_filepath = '/home/cla/Documentos/Vitor/DataCamp/Data-Scientist-with-Python/Datasets/young-people-survey-responses.csv'
student_data = pd.read_csv('/home/cla/Documentos/Vitor/DataCamp/Data-Scientist-with-Python/Datasets/student-alcohol-consumption.csv')
tips = sns.load_dataset('tips')
mpg = sns.load_dataset('mpg')
```

## **Introduction to relational plots and subplots**

## **Creating subplots with col and row**

We've seen in prior exercises that students with more absences (`"absences"`) tend to have lower final grades (`"G3"`). Does this relationship hold regardless of how much time students study each week?

To answer this, we'll look at the relationship between the number of absences that a student has in school and their final grade in the course, creating separate subplots based on each student's weekly study time (`"study_time"`).

Seaborn has been imported as `sns` and `matplotlib.pyplot` has been imported as `plt`.

## **Instructions**

1. Modify the code to use `relplot()` instead of `scatterplot()`.

2. Modify the code to create one scatter plot for each level of the variable `"study_time"`, arranged in columns.

3. Adapt your code to create one scatter plot for each level of a student's weekly study time, this time arranged in rows.

```{python}
fig, ax = plt.subplots()

# Change to use relplot() instead of scatterplot()
_ = sns.relplot(x = "absences", y = "G3", 
                data = student_data, 
                kind = 'scatter',
height = 2.6)

# Show plot
plt.show()

fig, ax = plt.subplots()

# Change to make subplots based on study time
_ = sns.relplot(x = "absences", y = "G3", 
                data = student_data, 
                kind = 'scatter', 
                col = 'study_time',
height = 2)

# Show plot
plt.show()

fig, ax = plt.subplots()

# Change this scatter plot to arrange the plots in rows instead of columns
_ = sns.relplot(x = "absences", y = "G3", 
                data = student_data, 
                kind = 'scatter', 
                row = 'study_time',
height = 2)

# Show plot
plt.show()
```

Because these subplots had a large range of x values, it's easier to read them arranged in rows instead of columns.

## **Creating two-factor subplots**

Let's continue looking at the `student_data` dataset of students in secondary school. Here, we want to answer the following question: does a student's first semester grade (`"G1"`) tend to correlate with their final grade (`"G3"`)?

There are many aspects of a student's life that could result in a higher or lower final grade in the class. For example, some students receive extra educational support from their school (`"schoolsup"`) or from their family (`"famsup"`), which could result in higher grades. Let's try to control for these two factors by creating subplots based on whether the student received extra educational support from their school or family.

Seaborn has been imported as `sns` and `matplotlib.pyplot` has been imported as `plt`.

## **Instructions**

- Use `relplot()` to create a scatter plot with `"G1"` on the x-axis and `"G3"` on the y-axis, using the `student_data` DataFrame.
- Create **column** subplots based on whether the student received support from the school (`"schoolsup"`), ordered so that "yes" comes before "no".
- Add **row** subplots based on whether the student received support from the family (`"famsup"`), ordered so that "yes" comes before "no". This will result in subplots based on two factors.

```{python}
fig, ax = plt.subplots()

# Create a scatter plot of G1 vs. G3
_ = sns.relplot(x = 'G1', y = 'G3', 
data = student_data,
kind =  'scatter',
height = 2.6)

# Show plot
plt.show()

fig, ax = plt.subplots()

# Adjust to add subplots based on school support
_ = sns.relplot(x = 'G1', y = 'G3', 
data = student_data,
kind =  'scatter',
col = 'schoolsup',
col_order = ['yes', 'no'],
height = 2)

# Show plot
plt.show()

fig, ax = plt.subplots()

# Adjust further to add subplots based on family support
_ = sns.relplot(x = 'G1', y = 'G3', 
data = student_data,
kind =  'scatter',
col = 'schoolsup',
row = 'famsup',
col_order = ['yes', 'no'],
row_order = ['yes', 'no'],
height = 1.3)

# Show plot
plt.show()
```

It looks like the first semester grade does correlate with the final grade, regardless of what kind of support the student received.

## **Customizing scatter plots**


**1. Customizing scatter plots**

So far, we've only scratched the surface of what we're able to do with scatter plots in Seaborn.

**2. Scatter plot overview**

As a reminder, scatter plots are a great tool for visualizing the relationship between two quantitative variables. We've seen a few ways to add more information to them as well, by creating subplots or plotting subgroups with different colored points. In addition to these, Seaborn allows you to add more information to scatter plots by varying the size, the style, and the transparency of the points. All of these options can be used in both the `"scatterplot()"` and `"relplot()"` functions, but we'll continue to use `"relplot()"` for the rest of the course since it's more flexible and allows us to create subplots. For the rest of this lesson, we'll use the tips dataset to learn how to use each customization and cover best practices for deciding which customizations to use.

**3. Subgroups with point size**

The first customization we'll talk about is point size. Here, we're creating a scatter plot of total bill versus tip amount. We want each point on the scatter plot to be sized based on the number of people in the group, with larger groups having bigger points on the plot. To do this, we'll set the "size" parameter equal to the variable name "size" from our dataset. As this example demonstrates, varying point size is best used if the variable is either a quantitative variable or a categorical variable that represents different levels of something, like "small", "medium", and "large". This plot is a bit hard to read because all of the points are of the same color.

```{python}
import seaborn as sns
import matplotlib.pytplot as plt

fig, ax = plt.subplots()

_ = sns.relplot(x = 'total_bill', y = 'tip',
                data = tips,
                kind = 'scatter',
                size = 'size',
                height = 2.6)
                
plt.show()
```

**4. Point size and hue**

We can make it easier by using the `"size"` parameter in combination with the `"hue"` parameter. To do this, set `"hue"` equal to the variable name `"size"`. Notice that because `"size"` is a quantitative variable, Seaborn will automatically color the points different shades of the same color instead of different colors per category value like we saw in previous plots. Now larger groups have both larger and darker points, which provides better contrast and makes the plot easier to read.

```{python}
import seaborn as sns
import matplotlib.pytplot as plt

fig, ax = plt.subplots()

_ = sns.relplot(x = 'total_bill', 
                y = 'tip',
                data = tips,
                kind = 'scatter',
                size = 'size',
                hue = 'size',
                height = 2.6)
                
plt.show()
```

**5. Subgroups with point style**

The next customization we'll look at is the point style. Setting the `"style"` parameter to a variable name will use different point styles for each value of the variable. Here's a scatter plot we've seen before, where we use `"hue"` to create different colored points based on smoking status. Setting `"style"` equal to `"smoker"` allows us to better distinguish these subgroups by plotting smokers with a different point style in addition to a different color.

```{python}
import seaborn as sns
import matplotlib.pytplot as plt

fig, ax = plt.subplots()

_ = sns.relplot(x = 'total_bill', 
                y = 'tip',
                data = tips,
                kind = 'scatter',
                hue = 'smoker',
                style = 'smoker',
                height = 2.6)
                
plt.show()
```

**6. Changing point transparency**

The last customization we'll look at is point transparency. Setting the `"alpha"` parameter to a value between 0 and 1 will vary the transparency of the points in the plot, with 0 being completely transparent and 1 being completely non-transparent. Here, we've set `"alpha"` equal to `0.4`. This customization can be useful when you have many overlapping points on the scatter plot, so you can see which areas of the plot have more or less observations.

```{python}
import seaborn as sns
import matplotlib.pytplot as plt

fig, ax = plt.subplots()

_ = sns.relplot(x = 'total_bill', 
                y = 'tip',
                data = tips,
                kind = 'scatter',
                alpha = 0.4,
                height = 2.6)
                
plt.show()
```

**7. Let's practice!**

This is just the beginning of what you can do to customize your Seaborn scatter plots. Make sure to check out the Seaborn documentation for more options like specifying specific sizes or point styles to use in your plots. For now, let's practice what we've learned!

## **Change the size of scatter plot points**

In this exercise, we'll explore Seaborn's `mpg` dataset, which contains one row per car model and includes information such as the year the car was made, the number of miles per gallon ("M.P.G.") it achieves, the power of its engine (measured in "horsepower"), and its country of origin.

What is the relationship between the power of a car's engine (`"horsepower"`) and its fuel efficiency (`"mpg"`)? And how does this relationship vary by the number of cylinders ('"cylinders"') the car has? Let's find out.

Let's continue to use `relplot()` instead of `scatterplot()` since it offers more flexibility.

**Instructions**

1. Use `relplot()` and the `mpg` DataFrame to create a scatter plot with '"horsepower"' on the x-axis and '"mpg"' on the y-axis. Vary the size of the points by the number of cylinders in the car (`"cylinders"`).
2. To make this plot easier to read, use `hue` to vary the color of the points by the number of cylinders in the car (`"cylinders"`).


```{python}
# Import Matplotlib and Seaborn
import matplotlib.pyplot as plt
import seaborn as sns

fig, ax = plt.subplots()

# Create scatter plot of horsepower vs. mpg
_ = sns.relplot(x = 'horsepower',
                y = 'mpg',
                data = mpg,
                kind = 'scatter',
                size = 'cylinders',
                hue = 'cylinders',
                height = 2.6)

# Show plot
plt.show()
```

Cars with higher horsepower tend to get a lower number of miles per gallon. They also tend to have a higher number of cylinders.

## **Change the style of scatter plot points**

Let's continue exploring Seaborn's `mpg` dataset by looking at the relationship between how fast a car can accelerate (`"acceleration"`) and its fuel efficiency (`"mpg"`). Do these properties vary by country of origin (`"origin"`)?

Note that the `"acceleration"` variable is the time to accelerate from 0 to 60 miles per hour, in seconds. Higher values indicate slower acceleration.

**Instructions**

Use `relplot()` and the `mpg` DataFrame to create a scatter plot with `"acceleration"` on the x-axis and `"mpg"` on the y-axis. Vary the style and color of the plot points by country of origin (`"origin"`).

```{python}
# Import Matplotlib and Seaborn
import matplotlib.pyplot as plt
import seaborn as sns

# Create a scatter plot of acceleration vs. mpg
_ = sns.relplot(x = 'acceleration',
                y = 'mpg',
                data = mpg,
                kind = 'scatter',
                style = 'origin',
                hue = 'origin',
                height = 2.6)

# Show plot
plt.show()
```

Cars from the USA tend to accelerate more quickly and get lower miles per gallon compared to cars from Europe and Japan.

## **Introduction to line plots**

**1. Introduction to line plots**

Hello! In this video we'll dive into a new type of relational plot: line plots.

**2. What are line plots?**

In Seaborn, we have two types of relational plots: scatter plots and line plots. While each point in a scatter plot is assumed to be an independent observation, line plots are the visualization of choice when we need to track the same thing over time. A common example is tracking the value of a company's stock over time, as shown here.

```{python}
```

**3. Air pollution data**

In this video, we'll be using data on the levels of air pollution in a city. There are many air collection stations around the city, each measuring the nitrogen dioxide level every hour for a single day. Long-term exposure to high levels of nitrogen dioxide can cause chronic lung diseases. Let's begin with the simple case where we have one data point per x-value. Here we have one row per hour over the course of the day with the average nitrogen dioxide level across all the stations in a column called `"NO_2_mean"`.

**4. Scatter plot**

This is a scatter plot with the average nitrogen dioxide level on the y-axis and the hour of the day on the x-axis. We're tracking the same thing over time, so a line plot would be a better choice.

```{python}

```

**5. Line plot**

By specifying `"kind"` equals `"line"`, we can create a line plot and more easily see how the average nitrogen dioxide level fluctuates throughout the day.

**6. Subgroups by location**

We can also track subgroups over time with line plots. Here we have the average nitrogen dioxide level for each region (North, South, East, and West) for each hour in the day.

```{python}

```

**7. Subgroups by location**

Setting the `"style"` and `"hue"` parameters equal to the variable name `"location"` creates different lines for each region that vary in both line style and color. Here, we can see that the South region tends to have slightly higher average nitrogen dioxide levels compared to the other regions.

```{python}

```

**8. Adding markers**

Setting the `"markers"` parameter equal to `"True"` will display a marker for each data point. The marker will vary based on the subgroup you've set using the `"style"` parameter.

```{python}

```

**9. Turning off line style**

If you don't want the line styles to vary by subgroup, set the `"dashes"` parameter equal to `"False"`.

```{python}

```

**10. Multiple observations per x-value**

Line plots can also be used when you have more than one observation per x-value. This dataset has a row for each station that is taking a measurement every hour.

```{python}

```

**11. Multiple observations per x-value**

This is the scatter plot, displaying one point per observation.

```{python}

```

**12. Multiple observations per x-value**

This is the line plot. If a line plot is given multiple observations per x-value, it will aggregate them into a single summary measure. By default, it will display the mean.

```{python}

```

**13. Multiple observations per x-value**

Notice that Seaborn will automatically calculate a confidence interval for the mean, displayed by the shaded region. Assuming the air collection stations were randomly placed throughout the city, this dataset is a random sample of the nitrogen dioxide levels across the whole city. This confidence interval tells us that based on our sample, we can be 95% confident that the average nitrogen dioxide level for the whole city is within this range. Confidence intervals indicate the uncertainty we have about what the true mean is for the whole city. To learn more about confidence intervals, you can check out DataCamp's statistics courses.

```{python}

```

**14. Replacing confidence interval with standard deviation**

Instead of visualizing a confidence interval, we may want to see how varied the measurements of nitrogen dioxide are across the different collection stations at a given point in time. To visualize this, set the `"ci"` parameter equal to the string `"sd"` to make the shaded area represent the standard deviation, which shows the spread of the distribution of observations at each x value.

**15. Turning off confidence interval**

We can also turn off the confidence interval by setting the `"ci"` parameter equal to `"None"`.

**16. Let's practice!**

Alright, time to practice what we've learned!

## **Interpreting line plots**

In this exercise, we'll continue to explore Seaborn's `mpg` dataset, which contains one row per car model and includes information such as the year the car was made, its fuel efficiency (measured in "miles per gallon" or "M.P.G"), and its country of origin (USA, Europe, or Japan).

How has the average miles per gallon achieved by these cars changed over time? Let's use line plots to find out!

**Instructions**

1. Use `relplot()` and the `mpg` DataFrame to create a line plot with `"model_year"` on the x-axis and `"mpg"` on the y-axis.

```{python}
# Import Matplotlib and Seaborn
import matplotlib.pyplot as plt
import seaborn as sns

fig, ax = plt.subplots()

# Create line plot
_ = sns.relplot(x = 'model_year',
                y = 'mpg',
                data = mpg,
                kind = 'line',
                height = 2.6)

# Show plot
plt.show()
```

The average miles per gallon has generally increased over time. 

## **Visualizing standard deviation with line plots**

In the last exercise, we looked at how the average miles per gallon achieved by cars has changed over time. Now let's use a line plot to visualize how the *distribution* of miles per gallon has changed over time.

Seaborn has been imported as `sns` and `matplotlib.pyplot` has been imported as `plt`.

**Instructions**

- Change the plot so the shaded area shows the standard deviation instead of the confidence interval for the mean.

```{python}
# Make the shaded area show the standard deviation
_ = sns.relplot(x = 'model_year',
                y = 'mpg',
                data = mpg,
                kind = 'line',
                ci = 'sd',
                height = 2.6)
# Show plot
plt.show()
```

Unlike the plot in the last exercise, this plot shows us the distribution of miles per gallon for all the cars in each year.

## **Plotting subgroups in linen plots**

Let's continue to look at the `mpg` dataset. We've seen that the average miles per gallon for cars has increased over time, but how has the average horsepower for cars changed over time? And does this trend differ by country of origin?

**Instructions**

- Use `relplot()` and the `mpg` DataFrame to create a line plot with `"model_year"` on the x-axis and `"horsepower"` on the y-axis. Turn off the confidence intervals on the plot.
- Create different lines for each country of origin (`"origin"`) that vary in both line style and color.
- Add markers for each data point to the lines.
- Use the `dashes` parameter to use solid lines for all countries, while still allowing for different marker styles for each line.

```{python}
# Import Matplotlib and Seaborn
import matplotlib.pyplot as plt
import seaborn as sns

fig, ax = plt.subplots()

# Create line plot of model year vs. horsepower
_ = sns.relplot(x = 'model_year',
                y = 'horsepower',
                data = mpg,
                kind = 'line',
                ci = None,
                height = 2.6)

# Show plot
plt.show()

fig, ax = plt.subplots()

# Change to create subgroups for country of origin
_ = sns.relplot(x = 'model_year',
                y = 'horsepower',
                data = mpg,
                kind = 'line',
                ci = None,
                style = 'origin',
                hue = 'origin',
                height = 2.6)

# Show plot
plt.show()

fig, ax = plt.subplots()

# Add markers and make each line have the same style
_ = sns.relplot(x = 'model_year',
                y = 'horsepower',
                data = mpg,
                kind = 'line',
                ci = None,
                style = 'origin',
                hue = 'origin',
                markers = True,
                dashes = False,
                height = 2.6)
                
# Show plot
plt.show()                
```

Now that we've added subgroups, we can see that this downward trend in horsepower was more pronounced among cars from the USA.